{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana7.fullname" . }}-sct
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "grafana7.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: {{ .Values.security.adminUsername | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.security.adminPassword | b64enc }}
  {{ if .Values.database.enabled -}}
  GF_DATABASE_USER: {{ .Values.database.auth.username | b64enc }}
  GF_DATABASE_PASSWORD: {{ .Values.database.auth.password | b64enc }}
  {{- end }}
{{- end -}}
