enabled: true
component: database
replicaCount: 1

# Create a LoadBalancer service for external Database access
loadBalancer:
  enabled: false

image:
  registry: postgis
  repository: postgis
  tag: 14-3.2-alpine
  pullPolicy: IfNotPresent

# Database settings
port: 5432
dbname: frost

auth:
  username: postgres
  password: changeMe

# Persistence settings
persistence:
  # Ommit trailing / !
  mountPath: /mydata
  pgdataSubPath: /pgdata
  accessModes:
    - ReadWriteOnce
  capacity: 4Gi

resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
