{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  type: ClusterIP
  selector:
    {{- include "caddy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.component }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{- end -}}
