{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frostdb.fullname" . }}-sct
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "frostdb.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.db.auth.username | default .Values.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.global.db.auth.password | default .Values.auth.password | b64enc }}

{{- end -}}
