{{- if .Values.enabled -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frostdb.fullname" . }}-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "frostdb.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  {{ if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{ end }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}

{{- end -}}
