{{- if .Values.enabled -}}
{{- if .Values.mqtt.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frostweb.fullname" . }}-mqtt
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "frostweb.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  type: {{ .Values.mqttService.type }}
  selector:
    {{- include "frostweb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.component }}
  ports:
    - name: mqtt
      protocol: TCP
      port: {{ .Values.mqttService.port }}
      targetPort: 1883
{{- end -}}
{{- end -}}
