apiVersion: v2
name: certIssuer
description: Helm chart to provide namespace Issuers for CertManager.
type: application

home: https://github.com/tum-gis/tum-gis-iot-stack-k8s
sources:
  - https://github.com/tum-gis/tum-gis-iot-stack-k8s/tree/main/helm/charts/charts/certIssuer

version: 0.4.1
appVersion: "0.1.0"

maintainers:
  - email: b.willenborg@tum.de
    name: Bruno Willenborg
    url: https://www.asg.ed.tum.de/en/gis/our-team/staff/bruno-willenborg/
