{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "frostweb.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  type: ClusterIP
  selector:
    {{- include "frostweb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.component }}
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mqtt-port
      protocol: TCP
      port: 1883
      targetPort: 1883
{{- end -}}
