{{- if .Values.enabled -}}
{{- if .Values.persistence.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nodered.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  serviceName: {{ include "nodered.fullname" . }}-hl
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodered.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.component }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/configmap-settings: {{ include (print $.Template.BasePath "/nodered-configMap-settings.yml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/nodered-configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/nodered-secret.yml") . | sha256sum }}
      labels:
        {{- include "nodered.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.component }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodered.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nodered.fullname" . }}
        - name: settings
          configMap:
            name: {{ include "nodered.fullname" . }}-settings

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP

          command: [ "node-red" ]
          args:
            - "-s"
            - "/settings/settings.js"
            - "-u"
            - {{ .Values.persistence.data.mountPath | quote }}

          envFrom:
            - configMapRef:
                name: {{ include "nodered.fullname" . }}
            - secretRef:
                name: {{ include "nodered.fullname" . }}

          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.startupProbe.terminationGracePeriodSeconds }}
            {{- with .Values.startupProbe.probe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.livenessProbe.terminationGracePeriodSeconds }}
            {{- with .Values.livenessProbe.probe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.readinessProbe.terminationGracePeriodSeconds }}
            {{- with .Values.readinessProbe.probe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
            - name: settings
              mountPath: "/settings"
              readOnly: true

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
{{- end -}}
