{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodered.fullname" . }}-cfg
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
data:
  TZ: {{ .Values.settings.tz | quote }}
  NODE_RED_ENABLE_PROJECTS: {{ .Values.settings.enableProjects | quote }}
  {{- if .Values.extraEnv -}}
  {{ toYaml .Values.extraEnv }}
  {{ end }}
{{- end -}}
