{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.component }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/grafana-configMap.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/grafana-secret.yml") . | sha256sum }}
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.component }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if not .Values.database.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}
      {{ end }}

      {{- if .Values.database.enabled }}
      initContainers:
        - name: pg-ready
          image: bwibo/k8s-init-container
          command:
            - pg_isready
          env:
            - name: PGHOST
              value: {{ .Values.database.host | quote }}
            - name: PGPORT
              value: {{ .Values.database.port | quote }}
            - name: PGUSER
              value: {{ .Values.database.auth.username | quote }}
            - name: PGPASSWORD
              value: {{ .Values.database.auth.password | quote }}
        - name: create-database
          image: bwibo/k8s-init-container
          args:
            - psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ .Values.database.dbname }}'" | grep -q 1 || psql -c "CREATE DATABASE {{ .Values.database.dbname }};"
          env:
            - name: PGHOST
              value: {{ .Values.database.host | quote }}
            - name: PGPORT
              value: {{ .Values.database.port | quote }}
            - name: PGUSER
              value: {{ .Values.database.auth.username | quote }}
            - name: PGPASSWORD
              value: {{ .Values.database.auth.password | quote }}

      #   - name: wait-for-psql
      #     image: bwibo/wait-for-psql
      #     args:
      #       - "60"
      #       - {{ .Values.database.host | quote }}
      #       - {{ .Values.database.port | quote }}
      #       - {{ .Values.database.dbname | quote }}
      #       - {{ .Values.database.auth.username | quote }}
      #       - {{ .Values.database.auth.password | squote }}
      {{ end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "grafana.fullname" . }}
            - secretRef:
                name: {{ include "grafana.fullname" . }}

          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.startupProbe.terminationGracePeriodSeconds }}
            {{- with .Values.startupProbe.probe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.livenessProbe.terminationGracePeriodSeconds }}
            {{- with .Values.livenessProbe.probe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.readinessProbe.terminationGracePeriodSeconds }}
            {{- with .Values.readinessProbe.probe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

      {{- if not .Values.database.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.data.mountPath }}
              name: data
      {{ end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
