{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: tum-gis-iot-stack-k8s
    app.kubernetes.io/component: {{ .Values.component }}
spec:
  type: ClusterIP
  selector:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.component }}
  ports:
    - name: http-port
      protocol: TCP
      port: 3000
      targetPort: 3000
{{- end -}}
